
local myname, ns = ...
local _, class = UnitClass("player")


ns.spec_weights = {}


if class == 'DEATHKNIGHT' then
  ns.spec_weights.Blood = {
    ITEM_MOD_STRENGTH_SHORT = 100,
    RESISTANCE0_NAME = 99,
    ITEM_MOD_MASTERY_RATING_SHORT = 85,
    ITEM_MOD_HASTE_RATING_SHORT = 80,
    ITEM_MOD_CRIT_RATING_SHORT = 70,
  }
  ns.spec_weights.Frost = {
    ITEM_MOD_STRENGTH_SHORT = 100,
    ITEM_MOD_HASTE_RATING_SHORT = 87,
    ITEM_MOD_MASTERY_RATING_SHORT = 79,
    ITEM_MOD_CRIT_RATING_SHORT = 67,
  }
  ns.spec_weights.Unholy = {
    ITEM_MOD_MASTERY_RATING_SHORT = 100,
    ITEM_MOD_STRENGTH_SHORT = 93,
    ITEM_MOD_HASTE_RATING_SHORT = 77,
    ITEM_MOD_CRIT_RATING_SHORT = 66,
  }
end


if class == 'DRUID' then
  ns.spec_weights.Balance = {
    ITEM_MOD_HASTE_RATING_SHORT = 100,
    ITEM_MOD_MASTERY_RATING_SHORT = 95,
    ITEM_MOD_INTELLECT_SHORT = 95,
    ITEM_MOD_SPELL_POWER_SHORT = 93,
    ITEM_MOD_CRIT_RATING_SHORT = 91,
  }
  ns.spec_weights.Feral = {
    ITEM_MOD_DAMAGE_PER_SECOND_SHORT = 113,
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 38,
    ITEM_MOD_MASTERY_RATING_SHORT = 30,
    ITEM_MOD_HASTE_RATING_SHORT = 27,
  }
  ns.spec_weights.Guardian = {
    RESISTANCE0_NAME = 100,
    ITEM_MOD_AGILITY_SHORT = 96,
    ITEM_MOD_MASTERY_RATING_SHORT = 80,
    ITEM_MOD_HASTE_RATING_SHORT = 70,
    ITEM_MOD_CRIT_RATING_SHORT = 60,
  }
  ns.spec_weights.Restoration = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 85,
    ITEM_MOD_SPIRIT_SHORT = 80,
    ITEM_MOD_HASTE_RATING_SHORT = 75,
    ITEM_MOD_MASTERY_RATING_SHORT = 65,
    ITEM_MOD_CRIT_RATING_SHORT = 60,
  }
end


if class == 'HUNTER' then
  ns.spec_weights.Beastmaster = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 80,
    ITEM_MOD_MASTERY_RATING_SHORT = 63,
    ITEM_MOD_HASTE_RATING_SHORT = 56,
  }
  ns.spec_weights.Marksmanship = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_MASTERY_RATING_SHORT = 79,
    ITEM_MOD_CRIT_RATING_SHORT = 69,
    ITEM_MOD_HASTE_RATING_SHORT = 58,
  }
  ns.spec_weights.Survival = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 69,
    ITEM_MOD_HASTE_RATING_SHORT = 61,
    ITEM_MOD_MASTERY_RATING_SHORT = 50,
  }
end


if class == 'MAGE' then
  ns.spec_weights.Arcane = {
    ITEM_MOD_HASTE_RATING_SHORT = 100,
    ITEM_MOD_MASTERY_RATING_SHORT = 99,
    ITEM_MOD_INTELLECT_SHORT = 95,
    ITEM_MOD_SPELL_POWER_SHORT = 94,
    ITEM_MOD_CRIT_RATING_SHORT = 93,
  }
  ns.spec_weights.Fire = {
    ITEM_MOD_CRIT_RATING_SHORT = 100,
    ITEM_MOD_MASTERY_RATING_SHORT = 87,
    ITEM_MOD_HASTE_RATING_SHORT = 81,
    ITEM_MOD_SPELL_POWER_SHORT = 70,
    ITEM_MOD_INTELLECT_SHORT = 70,
  }
  ns.spec_weights.Frost = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 99,
    ITEM_MOD_MASTERY_RATING_SHORT = 83,
    ITEM_MOD_CRIT_RATING_SHORT = 72,
    ITEM_MOD_HASTE_RATING_SHORT = 67,
  }
end


if class == 'MONK' then
  ns.spec_weights.Brewmaster = {
    RESISTANCE0_NAME = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 95,
    ITEM_MOD_MASTERY_RATING_SHORT = 78,
    ITEM_MOD_HASTE_RATING_SHORT = 63,
    ITEM_MOD_AGILITY_SHORT = 48,
  }
  ns.spec_weights.Mistweaver = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 85,
    ITEM_MOD_CRIT_RATING_SHORT = 80,
    ITEM_MOD_SPIRIT_SHORT = 75,
    ITEM_MOD_HASTE_RATING_SHORT = 60,
    ITEM_MOD_MASTERY_RATING_SHORT = 40,
  }
  ns.spec_weights.Windwalker = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_HASTE_RATING_SHORT = 98,
    ITEM_MOD_CRIT_RATING_SHORT = 75,
    ITEM_MOD_MASTERY_RATING_SHORT = 39,
  }
end


if class == 'PALADIN' then
  ns.spec_weights.Holy = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 80,
    ITEM_MOD_CRIT_RATING_SHORT = 75,
    ITEM_MOD_SPIRIT_SHORT = 70,
    ITEM_MOD_HASTE_RATING_SHORT = 55,
    ITEM_MOD_MASTERY_RATING_SHORT = 50,
  }
  ns.spec_weights.Protection = {
    ITEM_MOD_MASTERY_RATING_SHORT = 100,
    ITEM_MOD_STAMINA_SHORT = 96,
    RESISTANCE0_NAME = 95,
    ITEM_MOD_HASTE_RATING_SHORT = 74,
    ITEM_MOD_CRIT_RATING_SHORT = 71,
    ITEM_MOD_STRENGTH_SHORT = 49,
    ITEM_MOD_ATTACK_POWER_RATING_SHORT = 36,
  }
  ns.spec_weights.Retribution = {
    ITEM_MOD_STRENGTH_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 95,
    ITEM_MOD_MASTERY_RATING_SHORT = 78,
    ITEM_MOD_HASTE_RATING_SHORT = 27,
  }
end


if class == 'PRIEST' then
  ns.spec_weights.Discipline = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 81,
    ITEM_MOD_SPIRIT_SHORT = 80,
    ITEM_MOD_CRIT_RATING_SHORT = 65,
    ITEM_MOD_MASTERY_RATING_SHORT = 60,
    ITEM_MOD_HASTE_RATING_SHORT = 30,
  }
  ns.spec_weights.Holy = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 85,
    ITEM_MOD_SPIRIT_SHORT = 81,
    ITEM_MOD_MASTERY_RATING_SHORT = 75,
    ITEM_MOD_HASTE_RATING_SHORT = 62,
    ITEM_MOD_CRIT_RATING_SHORT = 43,
  }
  ns.spec_weights.Shadow = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 99,
    ITEM_MOD_CRIT_RATING_SHORT = 91,
    ITEM_MOD_MASTERY_RATING_SHORT = 87,
    ITEM_MOD_HASTE_RATING_SHORT = 84,
  }
end


if class == 'ROGUE' then
  ns.spec_weights.Assassination = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 84,
    ITEM_MOD_HASTE_RATING_SHORT = 71,
    ITEM_MOD_MASTERY_RATING_SHORT = 59,
  }
  ns.spec_weights.Combat = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 99,
    ITEM_MOD_MASTERY_RATING_SHORT = 76,
    ITEM_MOD_HASTE_RATING_SHORT = 57,
  }
  ns.spec_weights.Subtlety = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 84,
    ITEM_MOD_MASTERY_RATING_SHORT = 79,
    ITEM_MOD_HASTE_RATING_SHORT = 64,
  }
end


if class == 'SHAMAN' then
  ns.spec_weights.Elemental = {
    ITEM_MOD_CRIT_RATING_SHORT = 100,
    ITEM_MOD_HASTE_RATING_SHORT = 100,
    ITEM_MOD_MASTERY_RATING_SHORT = 97,
    ITEM_MOD_INTELLECT_SHORT = 95,
    ITEM_MOD_SPELL_POWER_SHORT = 93,
  }
  ns.spec_weights.Enhancement = {
    ITEM_MOD_AGILITY_SHORT = 100,
    ITEM_MOD_DAMAGE_PER_SECOND_SHORT = 99,
    ITEM_MOD_CRIT_RATING_SHORT = 70,
    ITEM_MOD_MASTERY_RATING_SHORT = 70,
    ITEM_MOD_HASTE_RATING_SHORT = 64,
  }
  ns.spec_weights.Restoration = {
    ITEM_MOD_INTELLECT_SHORT = 100,
    ITEM_MOD_SPELL_POWER_SHORT = 75,
    ITEM_MOD_SPIRIT_SHORT = 65,
    ITEM_MOD_CRIT_RATING_SHORT = 60,
    ITEM_MOD_MASTERY_RATING_SHORT = 58,
    ITEM_MOD_HASTE_RATING_SHORT = 50,
  }
end


if class == 'WARLOCK' then
  ns.spec_weights.Affliction = {
    ITEM_MOD_MASTERY_RATING_SHORT = 100,
    ITEM_MOD_INTELLECT_SHORT = 78,
    ITEM_MOD_SPELL_POWER_SHORT = 77,
    ITEM_MOD_HASTE_RATING_SHORT = 77,
    ITEM_MOD_CRIT_RATING_SHORT = 75,
  }
  ns.spec_weights.Demonology = {
    ITEM_MOD_MASTERY_RATING_SHORT = 100,
    ITEM_MOD_INTELLECT_SHORT = 90,
    ITEM_MOD_SPELL_POWER_SHORT = 89,
    ITEM_MOD_CRIT_RATING_SHORT = 82,
    ITEM_MOD_HASTE_RATING_SHORT = 65,
  }
  ns.spec_weights.Destruction = {
    ITEM_MOD_HASTE_RATING_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 97,
    ITEM_MOD_INTELLECT_SHORT = 89,
    ITEM_MOD_SPELL_POWER_SHORT = 88,
    ITEM_MOD_MASTERY_RATING_SHORT = 84,
  }
end


if class == 'WARRIOR' then
  ns.spec_weights.Arms = {
    ITEM_MOD_HASTE_RATING_SHORT = 100,
    ITEM_MOD_CRIT_RATING_SHORT = 68,
    ITEM_MOD_STRENGTH_SHORT = 61,
    ITEM_MOD_MASTERY_RATING_SHORT = 58,
  }
  ns.spec_weights.Fury = {
    ITEM_MOD_MASTERY_RATING_SHORT = 100,
    ITEM_MOD_HASTE_RATING_SHORT = 92,
    ITEM_MOD_CRIT_RATING_SHORT = 90,
    ITEM_MOD_STRENGTH_SHORT = 84,
  }
  ns.spec_weights.Protection = {
    ITEM_MOD_STRENGTH_SHORT = 100,
    RESISTANCE0_NAME = 90,
    ITEM_MOD_STAMINA_SHORT = 71,
    ITEM_MOD_CRIT_RATING_SHORT = 60,
    ITEM_MOD_MASTERY_RATING_SHORT = 51,
  }
end
