
local myname, ns = ...
local _, class = UnitClass("player")


ns.spec_weights = {}


if class == "DEATHKNIGHT" then
	ns.spec_weights.Blood = {
		RESISTANCE0_NAME = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 90,
		ITEM_MOD_HASTE_RATING_SHORT = 85,
		ITEM_MOD_STRENGTH_SHORT = 80,
		ITEM_MOD_VERSATILITY = 75,
		ITEM_MOD_CRIT_RATING_SHORT = 70,
		ITEM_MOD_MASTERY_RATING_SHORT = 60,
	}
	ns.spec_weights.Frost = {
		ITEM_MOD_STRENGTH_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 43,
		ITEM_MOD_VERSATILITY = 41,
		ITEM_MOD_HASTE_RATING_SHORT = 37,
		ITEM_MOD_MASTERY_RATING_SHORT = 36,
		ITEM_MOD_CRIT_RATING_SHORT = 35,
	}
	ns.spec_weights.Unholy = {
		ITEM_MOD_STRENGTH_SHORT = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 56,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 52,
		ITEM_MOD_CRIT_RATING_SHORT = 40,
		ITEM_MOD_VERSATILITY = 37,
		ITEM_MOD_HASTE_RATING_SHORT = 29,
	}
end


if class == "DRUID" then
	ns.spec_weights.Balance = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_HASTE_RATING_SHORT = 50,
		ITEM_MOD_MASTERY_RATING_SHORT = 49,
		ITEM_MOD_CRIT_RATING_SHORT = 46,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 46,
		ITEM_MOD_VERSATILITY = 39,
	}
	ns.spec_weights.Feral = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 46,
		ITEM_MOD_VERSATILITY = 38,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 38,
		ITEM_MOD_MASTERY_RATING_SHORT = 36,
		ITEM_MOD_HASTE_RATING_SHORT = 30,
	}
	ns.spec_weights.Guardian = {
		RESISTANCE0_NAME = 100,
		ITEM_MOD_AGILITY_SHORT = 96,
		ITEM_MOD_MASTERY_RATING_SHORT = 80,
		ITEM_MOD_VERSATILITY = 75,
		ITEM_MOD_HASTE_RATING_SHORT = 55,
		ITEM_MOD_CRIT_RATING_SHORT = 30,
	}
	ns.spec_weights.Restoration = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 85,
		ITEM_MOD_HASTE_RATING_SHORT = 75,
		ITEM_MOD_MASTERY_RATING_SHORT = 65,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 60,
		ITEM_MOD_CRIT_RATING_SHORT = 55,
		ITEM_MOD_VERSATILITY = 50,
	}
end


if class == "HUNTER" then
	ns.spec_weights.Beastmaster = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 40,
		ITEM_MOD_HASTE_RATING_SHORT = 38,
		ITEM_MOD_MASTERY_RATING_SHORT = 38,
		ITEM_MOD_VERSATILITY = 36,
		ITEM_MOD_CRIT_RATING_SHORT = 35,
	}
	ns.spec_weights.Marksmanship = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 46,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 45,
		ITEM_MOD_VERSATILITY = 41,
		ITEM_MOD_MASTERY_RATING_SHORT = 39,
		ITEM_MOD_HASTE_RATING_SHORT = 33,
	}
	ns.spec_weights.Survival = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 45,
		ITEM_MOD_VERSATILITY = 35,
		ITEM_MOD_CRIT_RATING_SHORT = 34,
		ITEM_MOD_MASTERY_RATING_SHORT = 28,
		ITEM_MOD_HASTE_RATING_SHORT = 14,
	}
end


if class == "MAGE" then
	ns.spec_weights.Arcane = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 55,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 48,
		ITEM_MOD_CRIT_RATING_SHORT = 44,
		ITEM_MOD_HASTE_RATING_SHORT = 41,
		ITEM_MOD_VERSATILITY = 39,
	}
	ns.spec_weights.Fire = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_HASTE_RATING_SHORT = 56,
		ITEM_MOD_MASTERY_RATING_SHORT = 55,
		ITEM_MOD_CRIT_RATING_SHORT = 55,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 50,
		ITEM_MOD_VERSATILITY = 38,
	}
	ns.spec_weights.Frost = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 60,
		ITEM_MOD_VERSATILITY = 45,
		ITEM_MOD_CRIT_RATING_SHORT = 44,
		ITEM_MOD_MASTERY_RATING_SHORT = 38,
		ITEM_MOD_HASTE_RATING_SHORT = 29,
	}
end


if class == "MONK" then
	ns.spec_weights.Brewmaster = {
		RESISTANCE0_NAME = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 90,
		ITEM_MOD_VERSATILITY = 85,
		ITEM_MOD_AGILITY_SHORT = 80,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 75,
		ITEM_MOD_CRIT_RATING_SHORT = 70,
		ITEM_MOD_HASTE_RATING_SHORT = 63,
	}
	ns.spec_weights.Mistweaver = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 90,
		ITEM_MOD_CRIT_RATING_SHORT = 80,
		ITEM_MOD_SPIRIT_SHORT = 75,
		ITEM_MOD_VERSATILITY = 65,
		ITEM_MOD_HASTE_RATING_SHORT = 60,
		ITEM_MOD_MASTERY_RATING_SHORT = 40,
	}
	ns.spec_weights.Windwalker = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 47,
		ITEM_MOD_CRIT_RATING_SHORT = 39,
		ITEM_MOD_VERSATILITY = 39,
		ITEM_MOD_HASTE_RATING_SHORT = 37,
		ITEM_MOD_MASTERY_RATING_SHORT = 23,
	}
end


if class == "PALADIN" then
	ns.spec_weights.Holy = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 90,
		ITEM_MOD_SPIRIT_SHORT = 85,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 80,
		ITEM_MOD_MASTERY_RATING_SHORT = 75,
		ITEM_MOD_VERSATILITY = 65,
		ITEM_MOD_HASTE_RATING_SHORT = 55,
	}
	ns.spec_weights.Protection = {
		RESISTANCE0_NAME = 100,
		ITEM_MOD_STRENGTH_SHORT = 89,
		ITEM_MOD_STAMINA_SHORT = 84,
		ITEM_MOD_MASTERY_RATING_SHORT = 80,
		ITEM_MOD_CRIT_RATING_SHORT = 70,
		ITEM_MOD_VERSATILITY = 69,
		ITEM_MOD_ATTACK_POWER_RATING_SHORT = 68,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 64,
		ITEM_MOD_HASTE_RATING_SHORT = 60,
	}
	ns.spec_weights.Retribution = {
		ITEM_MOD_STRENGTH_SHORT = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 56,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 45,
		ITEM_MOD_HASTE_RATING_SHORT = 44,
		ITEM_MOD_CRIT_RATING_SHORT = 44,
		ITEM_MOD_VERSATILITY = 41,
	}
end


if class == "PRIEST" then
	ns.spec_weights.Discipline = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 80,
		ITEM_MOD_CRIT_RATING_SHORT = 65,
		ITEM_MOD_MASTERY_RATING_SHORT = 60,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 55,
		ITEM_MOD_VERSATILITY = 45,
		ITEM_MOD_HASTE_RATING_SHORT = 30,
	}
	ns.spec_weights.Holy = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 81,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 75,
		ITEM_MOD_MASTERY_RATING_SHORT = 70,
		ITEM_MOD_CRIT_RATING_SHORT = 65,
		ITEM_MOD_VERSATILITY = 60,
		ITEM_MOD_HASTE_RATING_SHORT = 55,
	}
	ns.spec_weights.Shadow = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 51,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 48,
		ITEM_MOD_HASTE_RATING_SHORT = 47,
		ITEM_MOD_CRIT_RATING_SHORT = 44,
		ITEM_MOD_VERSATILITY = 39,
	}
end


if class == "ROGUE" then
	ns.spec_weights.Assassination = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_HASTE_RATING_SHORT = 41,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 40,
		ITEM_MOD_CRIT_RATING_SHORT = 37,
		ITEM_MOD_VERSATILITY = 36,
		ITEM_MOD_MASTERY_RATING_SHORT = 35,
	}
	ns.spec_weights.Combat = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 48,
		ITEM_MOD_MASTERY_RATING_SHORT = 39,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 35,
		ITEM_MOD_VERSATILITY = 34,
		ITEM_MOD_HASTE_RATING_SHORT = 30,
	}
	ns.spec_weights.Subtlety = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 44,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 42,
		ITEM_MOD_CRIT_RATING_SHORT = 36,
		ITEM_MOD_VERSATILITY = 35,
		ITEM_MOD_HASTE_RATING_SHORT = 23,
	}
end


if class == "SHAMAN" then
	ns.spec_weights.Elemental = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 80,
		ITEM_MOD_HASTE_RATING_SHORT = 70,
		ITEM_MOD_MASTERY_RATING_SHORT = 55,
		ITEM_MOD_CRIT_RATING_SHORT = 50,
		ITEM_MOD_VERSATILITY = 50,
	}
	ns.spec_weights.Enhancement = {
		ITEM_MOD_AGILITY_SHORT = 100,
		ITEM_MOD_HASTE_RATING_SHORT = 42,
		ITEM_MOD_MASTERY_RATING_SHORT = 38,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 38,
		ITEM_MOD_CRIT_RATING_SHORT = 35,
		ITEM_MOD_VERSATILITY = 35,
	}
	ns.spec_weights.Restoration = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 65,
		ITEM_MOD_CRIT_RATING_SHORT = 60,
		ITEM_MOD_MASTERY_RATING_SHORT = 58,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 50,
		ITEM_MOD_VERSATILITY = 45,
		ITEM_MOD_HASTE_RATING_SHORT = 40,
	}
end


if class == "WARLOCK" then
	ns.spec_weights.Affliction = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_MASTERY_RATING_SHORT = 56,
		ITEM_MOD_HASTE_RATING_SHORT = 53,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 47,
		ITEM_MOD_CRIT_RATING_SHORT = 43,
		ITEM_MOD_VERSATILITY = 39,
	}
	ns.spec_weights.Demonology = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_HASTE_RATING_SHORT = 50,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 46,
		ITEM_MOD_MASTERY_RATING_SHORT = 45,
		ITEM_MOD_CRIT_RATING_SHORT = 45,
		ITEM_MOD_VERSATILITY = 39,
	}
	ns.spec_weights.Destruction = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 49,
		ITEM_MOD_HASTE_RATING_SHORT = 44,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 43,
		ITEM_MOD_MASTERY_RATING_SHORT = 41,
		ITEM_MOD_VERSATILITY = 40,
	}
end


if class == "WARRIOR" then
	ns.spec_weights.Arms = {
		ITEM_MOD_STRENGTH_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 54,
		ITEM_MOD_MASTERY_RATING_SHORT = 52,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 46,
		ITEM_MOD_VERSATILITY = 42,
		ITEM_MOD_HASTE_RATING_SHORT = 33,
	}
	ns.spec_weights.Fury = {
		ITEM_MOD_STRENGTH_SHORT = 100,
		ITEM_MOD_CRIT_RATING_SHORT = 65,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 57,
		ITEM_MOD_MASTERY_RATING_SHORT = 57,
		ITEM_MOD_HASTE_RATING_SHORT = 51,
		ITEM_MOD_VERSATILITY = 46,
	}
	ns.spec_weights.Protection = {
		ITEM_MOD_VERSATILITY = 100,
		RESISTANCE0_NAME = 95,
		ITEM_MOD_MASTERY_RATING_SHORT = 84,
		ITEM_MOD_HASTE_RATING_SHORT = 74,
		ITEM_MOD_CRIT_RATING_SHORT = 68,
		ITEM_MOD_CR_MULTISTRIKE_SHORT = 63,
		ITEM_MOD_STRENGTH_SHORT = 58,
	}
end
