
local myname, ns = ...


ns.spec_weights = {
	Discipline = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 80,
		ITEM_MOD_SPELL_POWER_SHORT = 75,
		ITEM_MOD_MASTERY_RATING_SHORT = 60,
		ITEM_MOD_HASTE_RATING_SHORT = 50,
		ITEM_MOD_CRIT_RATING_SHORT = 40,
	},
	Holy = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 80,
		ITEM_MOD_SPELL_POWER_SHORT = 75,
		ITEM_MOD_HASTE_RATING_SHORT = 75,
		ITEM_MOD_MASTERY_RATING_SHORT = 70,
		ITEM_MOD_CRIT_RATING_SHORT = 50,
  },
	Shadow = {
		ITEM_MOD_INTELLECT_SHORT = 100,
		ITEM_MOD_SPIRIT_SHORT = 77,
		ITEM_MOD_SPELL_POWER_SHORT = 56,
		ITEM_MOD_HASTE_RATING_SHORT = 54,
		ITEM_MOD_HIT_RATING_SHORT = 54,
		ITEM_MOD_MASTERY_RATING_SHORT = 52,
		ITEM_MOD_CRIT_RATING_SHORT = 47,
  },
}
